### ISSUE TITLE
Can't generate the JAR files, mvn package runs into an Error

### ISSUE THREAD

**Issue by mrcodecloud** [groupdocs-viewer-cloud/groupdocs-viewer-cloud-java#2]
I am trying to build the JAR files using maven, to be used in my project but unfortunately I can't do it successfully. 
The command "mvn package" runs into an error while testing, details are mentioned in the attached screen shot. 

<img width="1290" alt="Screenshot at Aug 02 17-45-41" src="https://user-images.githubusercontent.com/6930624/127864498-8f3d5fb4-32b4-42eb-8e58-bafe2f224649.png">

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

By default Maven executes tests when running `mvn package`, there are a couple of options here:

1. Skip tests with `mvn package -Dmaven.test.skip=true`
2. Set `AppSID` and `AppKey` in [Config.java](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-java/blob/master/src/test/java/com/groupdocs/cloud/viewer/api/Config.java). You can get keys at https://dashboard.groupdocs.cloud/.

**Comment by mrcodecloud** [comment]
@vladimir-litvinchik  Thanks for the prompt response,
can you please guide, Where to place the AppSID, and AppKey ?

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

The `AppSID` and `AppKey` can be placed in `src\test\java\com\groupdocs\cloud\viewer\api\Config.java` file.

**Comment by mrcodecloud** [comment]
Thanks @vladimir-litvinchik  It's resolved, I am closing the issue

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

Thank you for the response! We've updated the [README](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-java#manual-build-and-installation-from-sources) to avoid such issues in the future.

Have a nice day!
