### ISSUE TITLE
groupdocs API isn't working always returns API Exception

### ISSUE THREAD

**Issue by mrcodecloud** [groupdocs-viewer-cloud/groupdocs-viewer-cloud-java#4]
@vladimir-litvinchik I am trying to build a sample android app for rendering the dwg files, but always getting API Exception error. Here is my sample app repo, can you please help? https://github.com/RAZA-ABBBASI/dwgviewer
<img width="1399" alt="Screenshot at Aug 10 18-41-31" src="https://user-images.githubusercontent.com/6930624/128877711-184a04a6-b471-470c-aa9e-8ff98645f059.png">

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

Thank you for posting the link to your repository. I have reproduced the issue. Please try performing the following steps:

1. In your [build.gradle](https://github.com/RAZA-ABBBASI/dwgviewer/blob/master/app/build.gradle#L46) file change `implementation 'com.groupdocs:groupdocs-viewer-cloud:21.8'` to `implementation 'com.groupdocs:groupdocs-viewer-cloud-android:21.8'` the [groupdocs-viewer-cloud-android](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-android) works better with Android Apps
2. Take [three-layouts.dwf](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-java/blob/master/resources/cad/dwf/three-layouts.dwf) file and place it in the root of your default storage at the [Dashboard](https://dashboard.groupdocs.cloud/files)
3. Update code in the [MainActivity.java](https://github.com/RAZA-ABBBASI/dwgviewer/blob/master/app/src/main/java/com/it22/myapplication/MainActivity.java#L94) and set the path to the file you want to process
```java
FileInfo fileInfo = new FileInfo(); 
fileInfo.setFilePath("three-layouts.dwf");
```
4. Run the app

In case you would like to upload a file from a device you'll need to upload a file to the storage first. Check [this test](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-android/blob/master/src/test/java/com/groupdocs/cloud/viewer/api/FileApiTests.java#L54) as an example.

**Comment by mrcodecloud** [comment]
@vladimir-litvinchik  Thank you so much for the response, I am late here but got it through a hard way that we first need the file to be tested at the storage first. Now I am looking into the file uploading part and will update you with the results. Thanks again for your prompt response.

**Comment by mrcodecloud** [comment]
Also I am curious, how I can use the response to view the rendered file in android?

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

The simplest scenario I can think of:
1. Upload a file into storage 
2. Process it by calling `createView` - this method will convert the file e.g. to HTML and place the output in [your storage](https://dashboard.groupdocs.cloud/files) in the `viewer` folder
3. Download output page(s) using file API
4. Render output page(s) in your Android App using the corresponding component e.g. [WebView](https://developer.android.com/reference/android/webkit/WebView)

Here is an [example ](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-android/blob/master/src/test/java/com/groupdocs/cloud/viewer/api/ViewerCreateViewApiTests.java#L78) that includes the second and third steps.

**Comment by mrcodecloud** [comment]
Thanks I am looking into it now.

**Comment by mrcodecloud** [comment]
@vladimir-litvinchik The code snippet you shared above is for testing [Test](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-android/blob/master/src/test/java/com/groupdocs/cloud/viewer/api/FileApiTests.java). Can you please share how I can upload file to the groupdocs cloud?

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

You can upload a file to storage by using `FileApi` like so

```java
Configuration configuration = new Configuration("app-sid", "app-key");
FileApi fileApi = new FileApi(configuration);

File file = getFile();
fileApi.uploadFile(new UploadFileRequest(path, file, null));
```

Here are some [tests](https://github.com/groupdocs-viewer-cloud/groupdocs-viewer-cloud-java/blob/master/src/test/java/com/groupdocs/cloud/viewer/api/FileApiTests.java#L41) that are using `FileApi`.

**Comment by mrcodecloud** [comment]
Not sure, why I am always getting an exception file not found I updated the repo, can you please have a look at it? 
MainActivity2.kt is the file we are working on now.

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

For the sake of simplicity, I have created a sample application https://github.com/vladimir-litvinchik/converting-file-to-html-and-downloading-output-with-cloud-sdk where you can find all the steps that have to be performed including uploading a file to storage and downloading the output.

**Comment by mrcodecloud** [comment]
@vladimir-litvinchik Thanks for your support. I just finished my sample app which performs the following 
1. File selection from the storage 
2. Uploading the selected file to the groupdocs storage
3. Rendering the DWG file 
4. Downloading the output file from groupdocs storage 
5. Viewing the downloaded HTML file 
You can find the source code here, 
https://github.com/RAZA-ABBBASI/dwgviewer 

It will be great help for the groupdocs android users, if you share it at groupdocs github examples page.

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

Great to hear that you have finished the sample app!

> It will be great help for the groupdocs android users, if you share it at groupdocs github examples page.

Do you mean adding a sample Android project that uses SDK to https://github.com/groupdocs-viewer-cloud?

**Comment by mrcodecloud** [comment]
Yes, Please

**Comment by vladimir-litvinchik** [comment]
@RAZA-ABBBASI 

I believe that it does make sense. We'll consider adding a sample app to the list of samples. Thank you for your suggestion!
